# Generated by Django 4.2.1 on 2023-05-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shepherd', '0002_remove_points_id_alter_points_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='username',
            new_name='user',
        ),
    ]
