# Generated by Django 4.2.1 on 2023-05-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shepherd', '0004_dailylogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailylogin',
            old_name='points',
            new_name='reward_points',
        ),
    ]
