# Generated by Django 4.2.1 on 2023-05-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shepherd', '0005_rename_points_dailylogin_reward_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailylogin',
            old_name='reward_points',
            new_name='points',
        ),
    ]
