# Generated by Django 4.2.1 on 2023-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shepherd', '0007_remove_dailylogin_login_date_dailylogin_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='last_action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
