# Generated by Django 4.2.1 on 2023-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shepherd', '0009_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('store', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
