# Generated by Django 4.2.1 on 2023-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shepherd', '0010_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price_now',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
