# Generated by Django 4.2.1 on 2023-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shepherd', '0011_items_price_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
