# Generated by Django 4.2.1 on 2023-07-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shepherd', '0014_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
