# Generated by Django 4.2.1 on 2023-07-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shepherd', '0010_message'),
        ('Shepherd', '0015_alter_items_image'),
    ]

    operations = [
    ]
